version: '3.8'
services:
  airbnb-properties-db:
    container_name: airbnb
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
volumes:
  mongo-data: